apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nscz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: POC
          value: POC
        image: quay.io/redhat-appstudio-qe/byoc-srvw-tenant/byoc-app-jsoo/nscz@sha256:fb4958039593a4e7e0ee24e261369cdbd46db7d29ab3e1ab05f1cd0c5f672655
        name: my-java-quarkus
        resources: {}
status: {}
