apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nscz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nscz
    app.kubernetes.io/part-of: byoc-app-jsoo
  name: nsczrknt
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: nscz
    weight: null
status: {}
